# Generated by Django 4.2.5 on 2024-01-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_password_email_alter_password_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
