# Generated by Django 4.2.5 on 2024-01-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_rename_password_password_enc_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='enc_password',
            new_name='password',
        ),
    ]
